### ISSUE TITLE
画面遷移図の作成

### ISSUE THREAD

**Issue by naoyamishina** [suzuyu0115/37seminor#1]

**Comment by naoyamishina** [comment]
### 画面遷移図のたたき台作成
- 画面の内容
  - ユーザー
    - 新規登録
    - 詳細
    - 編集
    - ログイン
  - クエスト（討伐会）投稿
    - 全一覧
    - 本日開催一覧
    - 新規作成
    - 編集 

https://www.figma.com/file/Fr37ooxPsRTB6KfAariKWQ/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB%E5%9B%B3?t=6G2oS57a9mIfZ5ZW-1

**Comment by MIDO-ruby7** [comment]
ハンターレベルとレベルアップめちゃくちゃいいですね！欲しい！実装方法のイメージがつかないのですが、案はありますか？(私も技術調査しておきます！)
1点気になったのはカリキュラム現在地です。RUNTEQのシステムと連動させるのは難しいので自分で更新していくと思うので、入門編、基礎編、応用編、卒業生とかざっくりでもいいかもしれません。カリキュラム進捗のgoogleスプレッドシートと連動させるとかできればいいのでしょうが…そこまでリソースかける部分でもなさそうなので。
アプリ名なども含めてまた話し合いたいです。

**Comment by naoyamishina** [comment]
- レベル上げについて
シンプルで簡単な方法でいいかなと考えてます！
ユーザーテーブル：レベルカラム、合計獲得経験値カラム
クエストテーブル：経験値カラムに入門編だと10, 基礎編だと20, 応用編だと30にしておく。（カリキュラム以外の勉強会としても使えればと思いますが、それ以外はとりあえず0想定）
閾値を50とかにして、ユーザーの合計獲得経験値を50で割った数字（少数切り捨て）をレベルに表記しようと思ってます！
参考：　https://qiita.com/nakasu1125/items/00858c399dfe6d89f3e4

- カリキュラム現在地
確かに詳細に分けるメリットなさそうなので、入門編、基礎編、応用編、卒業生をenumで入れるのがいいと思いました！

**Comment by MIDO-ruby7** [comment]
イメージ湧きました！ありがとうございます！私からはLGTMです
