### ISSUE TITLE
クエストの作成

### ISSUE THREAD

**Issue by naoyamishina** [suzuyu0115/37seminor#15]

**Comment by suzuyu0115** [comment]
クエスト作成画面のsubmitを押しても、createアクションが発火しない
ユーザーとのアソシエーションがないのが原因...？
ログを見たらデータは送られているが、DBには保存されていない

**Comment by suzuyu0115** [comment]
ユーザー機能、ログイン機能が作成されたら、作業ブランチにマージして挙動を確かめる
