### ISSUE TITLE
READMEの作成

### ISSUE THREAD

**Issue by suzuyu0115** [suzuyu0115/37seminor#2]

**Comment by suzuyu0115** [comment]
# サービス名

### 未定(討伐会アプリ)

## サービス概要

RUNTEQ受講生が課題の手助け(討伐)を気楽に募集、参加できる集会所(掲示板アプリ)です。

## ターゲットユーザー

- カリキュラムを進めているRUNTEQ生
- 課題で行き詰まり、モチベーションを無くしているRUNTEQ生
- 他人に教える行為により、課題への理解をより深めたい人

## ユーザーが抱える課題

- カリキュラムを進めているが、課題が難しく先へ進めない
- 課題がクリアできないことによるモチベーションの低下
- 他人にアウトプットして自分の理解度を試したいが中々機会が無い

## 解決方法

課題で行き詰まったがSOSを出せず、エスケープしてしまう受講生を減らすため、気軽に助けを求められるプラットフォームを提供します。

某ゲームのようなUIを実現することで、ゲーム感覚で募集、参加ができ、ユーザーの利用のハードルを軽減します。

## なぜこのサービスを作りたいのか

RUNTEQ37期には「討伐会」という文化があります。

討伐会とは、課題に行き詰まった受講生が同期等にヘルプを出し、集まった有志と共に課題解決にあたるという文化です。

この助け合いの文化により、37期の受講生の多くは挫折を乗り越え学習に励むことができています。

この文化がRUNTEQ全体に浸透すれば、挫折する受講生が減り、より多くの方が学習を終え、転職の夢を実現することができると考えました。

実際、内容が難しくなってから挫折し、エスケープしてしまった同期や先輩後輩を多く見てきました。

このアプリの浸透により、討伐会の文化が広まり、上記の様な方々の助けとなれば幸いです。

## 実装予定の機能

【MVPリリース】

- ユーザー登録機能
- ログイン・ログアウト機能
- クエスト依頼・削除機能
- クエスト閲覧・参加機能
- プロフィール機能

【本リリース】

- プロフィール機能
    - ランク機能
    - レベル機能
- ユーザー関連
    - パスワードリセット機能
- 管理者ユーザー
    - ユーザー管理(一覧・詳細・編集・削除)
    - クエスト管理(一覧・詳細・編集・削除)
- 利用規約
- プライバシーポリシー

## スケジュール

企画〜技術調査：3/10〆切

README〜ER図作成：3/18〆切

メイン機能実装：3/25〜4/6〆切

MVPリリース：4/7〆切

本番リリース：4/15〆切

**Comment by naoyamishina** [comment]
- 表現の好みですが、CRUDまとめた方が見やすいかも
【MVPリリース】
  - ユーザー登録機能
  - ログイン・ログアウト機能
  - クエスト作成・閲覧・編集・削除（CRUD）機能
  - クエスト参加機能
  - プロフィール機能

- クエストの削除機能どう思いますか？
クエストに人を募集中か完了済みかで、参加可否分ければ必要性どうなのかなと。
投稿数をできるだけ多く残したい思惑もあり。

**Comment by suzuyu0115** [comment]
> 表現の好みですが、CRUDまとめた方が見やすいかも

こちら修正しました！

> クエストの削除機能どう思いますか？

個人的にはなくてもいいかなと思います。
RUNTEQの質問フォームみたいに削除の代わりに解決済み(討伐済み)にしてもらう形でいいかも

> ユーザーにどうやって知ってもらう、浸透させるか

Twitter機能はマストで欲しいですね！このプラットフォーム上だけだと気づかれにくいと思うので。
開発頑張ります！！！

**Comment by MIDO-ruby7** [comment]
お二人ともありがとうございます！私もそれでいいと思います！
![LGTM](https://image.lgtmoon.dev/201552)

**Comment by suzuyu0115** [comment]
桓騎のLGTMかっこいいww
