### ISSUE TITLE
ER図の作成

### ISSUE THREAD

**Issue by suzuyu0115** [suzuyu0115/37seminor#3]

**Comment by suzuyu0115** [comment]
<img width="262" alt="ER" src="https://user-images.githubusercontent.com/113349377/224930334-2be426cf-d24b-45e3-868c-3e286e93e8cd.png">

**Comment by naoyamishina** [comment]
各テーブルとカラムの説明もらえるとありがたいです！

**Comment by suzuyu0115** [comment]
<img width="244" alt="37seminorer" src="https://user-images.githubusercontent.com/113349377/225206297-970915d1-4cc4-4c9c-993c-3b0336dfa431.png">

# 各テーブルのカラムについて
## 各テーブル共通
id: 主キー
created_atおよびupdated_at: 登録日時と更新日時

## Users
name: ユーザーの表示ネーム
email: ユーザーのメールアドレス
avatar: ユーザーのアバター写真
matriculation_day: ユーザーの入学日
curriculum: ユーザーの現在進行中のカリキュラム
rank: ユーザーのランク
experience_point: ランクに紐づくユーザーの経験値
role: 管理者か一般ユーザーかの判別(enum)
crypted_passwordおよびsalt: 暗号化されたパスワード
reset_password_token、reset_password_token_expires_at、reset_password_email_sent_at および access_count_to_reset_password_page: パスワードリセット用
## posts
user_id: クエスト投稿したユーザーを特定する外部キー
title: 投稿するクエスト名
datetime: クエストの開催日時
place: クエストの開催場所
body: クエストの困りごと、詳細などを記載するカラム
step: 基礎ステップ、応用ステップなど課題の段階を登録(enum)
state: 課題が未討伐か、討伐完了したかの旨を登録(enum)
## joins
post_id: 討伐参加した投稿を特定する外部キー
user_id: 討伐参加したユーザーを特定する外部キー
comment: コメント内容

**Comment by suzuyu0115** [comment]
こちら修正しました！
テーブルも修正したので確認をお願いします！

**Comment by naoyamishina** [comment]
レベル機能のため、課題ごと（入門編と基礎編など）に得られる経験値を分ける想定で、postにexpカラム入れてユーザーが獲得するポイントのカラム入れていいかなと！(enum)
テーブル名questでもいいかなと思ったけどお任せします！

**Comment by suzuyu0115** [comment]
> レベル機能のため、課題ごと（入門編と基礎編など）に得られる経験値を分ける想定で、postにexpカラム入れてユーザーが獲得するポイントのカラム入れていいかなと！(enum)

- カラム名を`posts`から`quests`に変更
- `quests`テーブルに`exp`カラムを追加

確認お願いします！

**Comment by naoyamishina** [comment]
OKです！
